# Generated by Django 4.0.5 on 2022-07-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_account_taken_test_alter_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=1)),
            ],
        ),
    ]
